# =============================================================================
# Before you start changing anything here, read the comments.
# All of them can be found below in the "DEFAULT" section

[DEFAULT]

# The directory that contains extracted files of everything you've downloaded.
#data_dir = "processed_datasets/tiny"
data_dir = "checkpoints"

# Train, dev and test jsonlines
train_data = "preprocessed_data/preco/english_train_head.jsonl"
dev_data = "preprocessed_data/preco/english_dev_head.jsonl"
test_data = "preprocessed_data/preco/english_test_head.jsonl"

# The directory that will contain conll prediction files
conll_log_dir = "data/conll_logs"
